---
# Configuration file, to deploy the BootCamp2020 projects on Surge

name: "Deploy Covid Tracker on Surge.sh."

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      #- name: Prepare for Yarn Installation
      #  run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      #- name: install yarn
      #  run: sudo apt update && sudo apt install yarn
      - name: Install Chartjs
        run: npm install --save react-chartjs-2 chart.js
      - name: Install Material UI
        run: npm install @material-ui/core
      - name: Install React Number Format
        run: npm install react-number-format --save
      - name: Build React App
        run: |
         npm install 
         CI=false npm run build 
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build bcamp20_covid_track.surge.sh --token ${{ secrets.PROJ002_SECRET }}